---
- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: Install package
    package:
      name:
       - htop
       - wget
       - tmux
       - vim
       - apache2
       - nginx

#  - name : copy nginx config file
#    copy: src=default dest=/etc/nginx/sites-available
# - name : restart nginx
#    service: name=nginx state=restarted

